import { env } from "cloudflare:test";
import { beforeEach, describe, expect, it } from "vitest";
import { resetDb } from "../helpers/db-reset";
import { callTool, connectMcp } from "../helpers/mcp-harness";
import { api, apiJson } from "../helpers/rest-client";
import { seedUser, testContext, testDb } from "../helpers/seed";

beforeEach(resetDb);

// Transport-agnostic snapshot: excludes autogenerated ids/timestamps/rank so
// only the meaningful domain state is compared.
async function snapshot() {
  const tasks = await env.DB.prepare(
    `SELECT id, title, quadrant, status, (completed_at IS NOT NULL) AS hasCompleted
       FROM tasks ORDER BY rank`,
  ).all<{
    id: string;
    title: string;
    quadrant: string | null;
    status: string;
    hasCompleted: number;
  }>();

  const out = [];
  for (const t of tasks.results) {
    const dod = await env.DB.prepare(
      "SELECT text, done FROM dod_criteria WHERE task_id = ? ORDER BY rank",
    )
      .bind(t.id)
      .all<{ text: string; done: number }>();
    const subs = await env.DB.prepare(
      "SELECT title, done FROM subtasks WHERE task_id = ? ORDER BY rank",
    )
      .bind(t.id)
      .all<{ title: string; done: number }>();
    out.push({
      title: t.title,
      quadrant: t.quadrant,
      status: t.status,
      hasCompleted: !!t.hasCompleted,
      dod: dod.results.map((d) => ({ text: d.text, done: !!d.done })),
      subtasks: subs.results.map((s) => ({ title: s.title, done: !!s.done })),
    });
  }
  return out;
}

async function runScenarioRest() {
  const t = await apiJson<{ id: string; dod: Array<{ id: string }> }>(
    "POST",
    "/api/tasks",
    { title: "Plan", quadrant: "q1" },
  );
  const withDod = await apiJson<{ dod: Array<{ id: string }> }>(
    "POST",
    `/api/tasks/${t.id}/dod`,
    { text: "d1" },
  );
  await api("PATCH", `/api/dod/${withDod.dod[0].id}`, { done: true });
  await api("PATCH", `/api/tasks/${t.id}`, { status: "done" });
  await api("POST", `/api/tasks/${t.id}/subtasks`, { title: "s1" });
}

async function runScenarioMcp() {
  const client = await connectMcp(testDb(), testContext());
  const t = await callTool(client, "create_task", {
    title: "Plan",
    quadrant: "q1",
  });
  const withDod = await callTool(client, "add_dod", {
    taskId: t.data.id,
    text: "d1",
  });
  await callTool(client, "toggle_dod", {
    dodId: withDod.data.dod[0].id,
    done: true,
  });
  await callTool(client, "update_task", { id: t.data.id, status: "done" });
  await callTool(client, "add_subtask", { taskId: t.data.id, title: "s1" });
}

describe("REST/MCP parity (H5, SERIAL)", () => {
  it("both surfaces yield identical domain state for the same scenario", async () => {
    // 1) REST run
    await runScenarioRest();
    const restSnapshot = await snapshot();

    // 2) reset D1, then MCP run (serial, never parallel)
    await resetDb();
    await seedUser();
    await runScenarioMcp();
    const mcpSnapshot = await snapshot();

    expect(mcpSnapshot).toEqual(restSnapshot);
    // sanity: the scenario actually produced the expected shape
    expect(restSnapshot).toEqual([
      {
        title: "Plan",
        quadrant: "q1",
        status: "done",
        hasCompleted: true,
        dod: [{ text: "d1", done: true }],
        subtasks: [{ title: "s1", done: false }],
      },
    ]);
  });
});
