/// <reference types="@cloudflare/vitest-pool-workers/types" />
import type { D1Migration } from "cloudflare:test";

// `cloudflare:test`'s `env` is typed as `Cloudflare.Env` (generated by
// `wrangler types`). Add the test-only migrations binding to it.
declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}
